// Extracts color values from the design tokens / variables into lib/tokens.ts.
//
//   node scripts/extract-tokens.mjs
//
// Sources (the in-repo source of truth, generated from the Figma export):
//   - app/globals.css                       → semantic theme tokens (light + dark)
//   - .claude/skills/.../references/DESIGN.md → Tailwind palette primitives (§B)
//
// Output: lib/tokens.ts (AUTO-GENERATED — do not edit by hand).

import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")

/* ---------------------------------------- semantic theme tokens (globals.css) */

const css = readFileSync(join(root, "app/globals.css"), "utf8")

function parseBlock(selector) {
  const re = new RegExp(`${selector}\\s*\\{([\\s\\S]*?)\\}`, "m")
  const body = css.match(re)?.[1] ?? ""
  const out = {}
  for (const m of body.matchAll(/--([\w-]+):\s*([^;]+);/g)) {
    out[m[1]] = m[2].trim()
  }
  return out
}

const light = parseBlock(":root")
const dark = parseBlock("\\.dark")

const themeTokens = Object.keys(light).map((name) => ({
  name,
  light: light[name],
  dark: dark[name] ?? light[name],
}))

/* ------------------------------------------ palette primitives (DESIGN.md §B) */

const design = readFileSync(
  join(
    root,
    ".claude/skills/shadcn-ui-design/references/DESIGN.md",
  ),
  "utf8",
)

// isolate §B section
const sectionB = design.slice(
  design.indexOf("## §B"),
  design.indexOf("## §C"),
)

const scaleMap = new Map()
for (const m of sectionB.matchAll(/`([a-z]+)\/(\d+)`\s*\|\s*`(oklch\([^`]+)`/g)) {
  const [, scale, step, value] = m
  if (!scaleMap.has(scale)) scaleMap.set(scale, new Map())
  scaleMap.get(scale).set(Number(step), value.trim())
}

const SCALE_ORDER = [
  "blue", "slate", "gray", "zinc", "neutral", "stone",
  "red", "orange", "amber", "yellow", "lime", "green", "emerald",
  "teal", "cyan", "sky", "indigo", "violet", "purple", "fuchsia", "pink", "rose",
]

const orderedScales = [...scaleMap.keys()].sort((a, b) => {
  const ia = SCALE_ORDER.indexOf(a)
  const ib = SCALE_ORDER.indexOf(b)
  return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib) || a.localeCompare(b)
})

const palette = orderedScales.map((scale) => ({
  name: scale,
  swatches: [...scaleMap.get(scale).entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([step, value]) => ({ step: String(step), value })),
}))

const swatchCount = palette.reduce((n, s) => n + s.swatches.length, 0)

/* ------------------------------------------------------------------- emit TS */

const banner =
  "// AUTO-GENERATED by scripts/extract-tokens.mjs — do not edit by hand.\n" +
  "// Run `node scripts/extract-tokens.mjs` to regenerate from the design tokens.\n\n"

const ts =
  banner +
  "export interface ThemeToken {\n" +
  "  name: string\n  light: string\n  dark: string\n}\n\n" +
  "export interface PaletteScale {\n" +
  "  name: string\n  swatches: { step: string; value: string }[]\n}\n\n" +
  `export const themeTokens: ThemeToken[] = ${JSON.stringify(themeTokens, null, 2)}\n\n` +
  `export const palette: PaletteScale[] = ${JSON.stringify(palette, null, 2)}\n`

writeFileSync(join(root, "lib/tokens.ts"), ts)

console.log(
  `✓ lib/tokens.ts — ${themeTokens.length} theme tokens, ` +
    `${palette.length} palette scales, ${swatchCount} swatches`,
)
