// AUTO-GENERATED by scripts/extract-tokens.mjs — do not edit by hand.
// Run `node scripts/extract-tokens.mjs` to regenerate from the design tokens.

export interface ThemeToken {
  name: string
  light: string
  dark: string
}

export interface PaletteScale {
  name: string
  swatches: { step: string; value: string }[]
}

export const themeTokens: ThemeToken[] = [
  {
    "name": "background",
    "light": "oklch(1 0 0)",
    "dark": "oklch(0.145 0 0)"
  },
  {
    "name": "foreground",
    "light": "oklch(0.145 0 0)",
    "dark": "oklch(0.985 0 0)"
  },
  {
    "name": "card",
    "light": "oklch(1 0 0)",
    "dark": "oklch(0.205 0 0)"
  },
  {
    "name": "card-foreground",
    "light": "oklch(0.145 0 0)",
    "dark": "oklch(0.985 0 0)"
  },
  {
    "name": "popover",
    "light": "oklch(1 0 0)",
    "dark": "oklch(0.269 0 0)"
  },
  {
    "name": "popover-foreground",
    "light": "oklch(0.145 0 0)",
    "dark": "oklch(0.985 0 0)"
  },
  {
    "name": "primary",
    "light": "oklch(0.546 0.215 262.9)",
    "dark": "oklch(0.546 0.215 262.9)"
  },
  {
    "name": "primary-foreground",
    "light": "oklch(0.985 0 0)",
    "dark": "oklch(0.205 0 0)"
  },
  {
    "name": "secondary",
    "light": "oklch(0.97 0 0)",
    "dark": "oklch(0.269 0 0)"
  },
  {
    "name": "secondary-foreground",
    "light": "oklch(0.145 0 0)",
    "dark": "oklch(0.985 0 0)"
  },
  {
    "name": "muted",
    "light": "oklch(0.97 0 0)",
    "dark": "oklch(0.269 0 0)"
  },
  {
    "name": "muted-foreground",
    "light": "oklch(0.556 0 0)",
    "dark": "oklch(0.715 0 0)"
  },
  {
    "name": "accent",
    "light": "oklch(0.97 0 0)",
    "dark": "oklch(0.371 0 0)"
  },
  {
    "name": "accent-foreground",
    "light": "oklch(0.205 0 0)",
    "dark": "oklch(0.985 0 0)"
  },
  {
    "name": "destructive",
    "light": "oklch(0.577 0.215 27.3)",
    "dark": "oklch(0.711 0.166 22.2)"
  },
  {
    "name": "border",
    "light": "oklch(0.922 0 0)",
    "dark": "oklch(0.371 0 0)"
  },
  {
    "name": "input",
    "light": "oklch(0.922 0 0)",
    "dark": "oklch(0.205 0 0)"
  },
  {
    "name": "ring",
    "light": "oklch(0.623 0.188 259.8)",
    "dark": "oklch(0.623 0.188 259.8)"
  },
  {
    "name": "chart-1",
    "light": "oklch(0.734 0.121 243.1)",
    "dark": "oklch(0.734 0.121 243.1)"
  },
  {
    "name": "chart-2",
    "light": "oklch(0.649 0.193 251.8)",
    "dark": "oklch(0.649 0.193 251.8)"
  },
  {
    "name": "chart-3",
    "light": "oklch(0.622 0.183 251.7)",
    "dark": "oklch(0.622 0.183 251.7)"
  },
  {
    "name": "chart-4",
    "light": "oklch(0.556 0.162 252.2)",
    "dark": "oklch(0.556 0.162 252.2)"
  },
  {
    "name": "chart-5",
    "light": "oklch(0.324 0.096 258.8)",
    "dark": "oklch(0.324 0.096 258.8)"
  },
  {
    "name": "sidebar",
    "light": "oklch(0.985 0 0)",
    "dark": "oklch(0.205 0 0)"
  },
  {
    "name": "sidebar-foreground",
    "light": "oklch(0.145 0 0)",
    "dark": "oklch(0.985 0 0)"
  },
  {
    "name": "sidebar-primary",
    "light": "oklch(0.205 0 0)",
    "dark": "oklch(0.622 0.183 251.7)"
  },
  {
    "name": "sidebar-primary-foreground",
    "light": "oklch(0.985 0 0)",
    "dark": "oklch(0.985 0 0)"
  },
  {
    "name": "sidebar-accent",
    "light": "oklch(0.97 0 0)",
    "dark": "oklch(0.269 0 0)"
  },
  {
    "name": "sidebar-accent-foreground",
    "light": "oklch(0.205 0 0)",
    "dark": "oklch(0.985 0 0)"
  },
  {
    "name": "sidebar-border",
    "light": "oklch(0.87 0 0)",
    "dark": "oklch(1 0 0 / 80%)"
  },
  {
    "name": "sidebar-ring",
    "light": "oklch(0.556 0 0)",
    "dark": "oklch(0.556 0 0)"
  },
  {
    "name": "background-color",
    "light": "oklch(0 0 0 / 30%)",
    "dark": "oklch(0 0 0 / 30%)"
  },
  {
    "name": "semantic-background",
    "light": "oklch(0.551 0.023 264.4)",
    "dark": "oklch(0.373 0.031 259.7)"
  },
  {
    "name": "semantic-border",
    "light": "oklch(0.446 0.026 256.8)",
    "dark": "oklch(0.446 0.026 256.8)"
  },
  {
    "name": "semantic-foreground",
    "light": "oklch(1 0 0)",
    "dark": "oklch(1 0 0)"
  }
]

export const palette: PaletteScale[] = [
  {
    "name": "blue",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.97 0.014 254.6)"
      },
      {
        "step": "100",
        "value": "oklch(0.932 0.032 255.6)"
      },
      {
        "step": "200",
        "value": "oklch(0.882 0.057 254.1)"
      },
      {
        "step": "300",
        "value": "oklch(0.809 0.096 251.8)"
      },
      {
        "step": "400",
        "value": "oklch(0.714 0.143 254.6)"
      },
      {
        "step": "500",
        "value": "oklch(0.623 0.188 259.8)"
      },
      {
        "step": "600",
        "value": "oklch(0.546 0.215 262.9)"
      },
      {
        "step": "700",
        "value": "oklch(0.488 0.217 264.4)"
      },
      {
        "step": "800",
        "value": "oklch(0.424 0.181 265.6)"
      },
      {
        "step": "900",
        "value": "oklch(0.379 0.138 265.5)"
      },
      {
        "step": "950",
        "value": "oklch(0.282 0.087 267.9)"
      }
    ]
  },
  {
    "name": "slate",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.984 0.003 247.9)"
      },
      {
        "step": "100",
        "value": "oklch(0.968 0.007 247.9)"
      },
      {
        "step": "200",
        "value": "oklch(0.929 0.013 255.5)"
      },
      {
        "step": "300",
        "value": "oklch(0.869 0.02 252.9)"
      },
      {
        "step": "400",
        "value": "oklch(0.711 0.035 256.8)"
      },
      {
        "step": "500",
        "value": "oklch(0.554 0.041 257.4)"
      },
      {
        "step": "600",
        "value": "oklch(0.446 0.037 257.3)"
      },
      {
        "step": "700",
        "value": "oklch(0.372 0.039 257.3)"
      },
      {
        "step": "800",
        "value": "oklch(0.279 0.037 260)"
      },
      {
        "step": "900",
        "value": "oklch(0.208 0.04 265.8)"
      },
      {
        "step": "950",
        "value": "oklch(0.129 0.041 264.7)"
      }
    ]
  },
  {
    "name": "gray",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.985 0.002 247.8)"
      },
      {
        "step": "100",
        "value": "oklch(0.967 0.003 264.5)"
      },
      {
        "step": "200",
        "value": "oklch(0.928 0.006 264.5)"
      },
      {
        "step": "300",
        "value": "oklch(0.872 0.009 258.3)"
      },
      {
        "step": "400",
        "value": "oklch(0.714 0.019 261.3)"
      },
      {
        "step": "500",
        "value": "oklch(0.551 0.023 264.4)"
      },
      {
        "step": "600",
        "value": "oklch(0.446 0.026 256.8)"
      },
      {
        "step": "700",
        "value": "oklch(0.373 0.031 259.7)"
      },
      {
        "step": "800",
        "value": "oklch(0.278 0.03 256.8)"
      },
      {
        "step": "900",
        "value": "oklch(0.21 0.032 264.7)"
      },
      {
        "step": "950",
        "value": "oklch(0.13 0.027 261.7)"
      }
    ]
  },
  {
    "name": "zinc",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.985 0 0)"
      },
      {
        "step": "100",
        "value": "oklch(0.967 0.001 286.4)"
      },
      {
        "step": "200",
        "value": "oklch(0.92 0.004 286.3)"
      },
      {
        "step": "300",
        "value": "oklch(0.871 0.005 286.3)"
      },
      {
        "step": "400",
        "value": "oklch(0.712 0.013 286.1)"
      },
      {
        "step": "500",
        "value": "oklch(0.552 0.014 285.9)"
      },
      {
        "step": "600",
        "value": "oklch(0.442 0.015 285.8)"
      },
      {
        "step": "700",
        "value": "oklch(0.37 0.012 285.8)"
      },
      {
        "step": "800",
        "value": "oklch(0.274 0.005 286)"
      },
      {
        "step": "900",
        "value": "oklch(0.21 0.006 285.9)"
      },
      {
        "step": "950",
        "value": "oklch(0.141 0.004 285.8)"
      }
    ]
  },
  {
    "name": "neutral",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.985 0 0)"
      },
      {
        "step": "100",
        "value": "oklch(0.97 0 0)"
      },
      {
        "step": "200",
        "value": "oklch(0.922 0 0)"
      },
      {
        "step": "300",
        "value": "oklch(0.87 0 0)"
      },
      {
        "step": "400",
        "value": "oklch(0.715 0 0)"
      },
      {
        "step": "500",
        "value": "oklch(0.556 0 0)"
      },
      {
        "step": "600",
        "value": "oklch(0.439 0 0)"
      },
      {
        "step": "700",
        "value": "oklch(0.371 0 0)"
      },
      {
        "step": "800",
        "value": "oklch(0.269 0 0)"
      },
      {
        "step": "900",
        "value": "oklch(0.205 0 0)"
      },
      {
        "step": "950",
        "value": "oklch(0.145 0 0)"
      }
    ]
  },
  {
    "name": "stone",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.985 0.001 106.4)"
      },
      {
        "step": "100",
        "value": "oklch(0.97 0.001 106.4)"
      },
      {
        "step": "200",
        "value": "oklch(0.923 0.003 48.7)"
      },
      {
        "step": "300",
        "value": "oklch(0.869 0.004 56.4)"
      },
      {
        "step": "400",
        "value": "oklch(0.716 0.009 56.3)"
      },
      {
        "step": "500",
        "value": "oklch(0.553 0.012 58.1)"
      },
      {
        "step": "600",
        "value": "oklch(0.444 0.01 73.6)"
      },
      {
        "step": "700",
        "value": "oklch(0.374 0.009 67.6)"
      },
      {
        "step": "800",
        "value": "oklch(0.268 0.006 34.3)"
      },
      {
        "step": "900",
        "value": "oklch(0.216 0.006 56)"
      },
      {
        "step": "950",
        "value": "oklch(0.147 0.004 49.2)"
      }
    ]
  },
  {
    "name": "red",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.971 0.013 17.4)"
      },
      {
        "step": "100",
        "value": "oklch(0.936 0.031 17.7)"
      },
      {
        "step": "200",
        "value": "oklch(0.885 0.059 18.3)"
      },
      {
        "step": "300",
        "value": "oklch(0.808 0.103 19.6)"
      },
      {
        "step": "400",
        "value": "oklch(0.711 0.166 22.2)"
      },
      {
        "step": "500",
        "value": "oklch(0.637 0.208 25.3)"
      },
      {
        "step": "600",
        "value": "oklch(0.577 0.215 27.3)"
      },
      {
        "step": "700",
        "value": "oklch(0.505 0.19 27.5)"
      },
      {
        "step": "800",
        "value": "oklch(0.444 0.161 26.9)"
      },
      {
        "step": "900",
        "value": "oklch(0.396 0.133 25.7)"
      },
      {
        "step": "950",
        "value": "oklch(0.258 0.089 26)"
      }
    ]
  },
  {
    "name": "orange",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.98 0.016 73.7)"
      },
      {
        "step": "100",
        "value": "oklch(0.954 0.037 75.2)"
      },
      {
        "step": "200",
        "value": "oklch(0.901 0.073 70.7)"
      },
      {
        "step": "300",
        "value": "oklch(0.837 0.117 66.3)"
      },
      {
        "step": "400",
        "value": "oklch(0.758 0.159 55.9)"
      },
      {
        "step": "500",
        "value": "oklch(0.705 0.187 47.6)"
      },
      {
        "step": "600",
        "value": "oklch(0.646 0.194 41.1)"
      },
      {
        "step": "700",
        "value": "oklch(0.553 0.174 38.4)"
      },
      {
        "step": "800",
        "value": "oklch(0.47 0.143 37.3)"
      },
      {
        "step": "900",
        "value": "oklch(0.408 0.116 38.2)"
      },
      {
        "step": "950",
        "value": "oklch(0.266 0.076 36.3)"
      }
    ]
  },
  {
    "name": "amber",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.987 0.021 95.3)"
      },
      {
        "step": "100",
        "value": "oklch(0.962 0.058 95.6)"
      },
      {
        "step": "200",
        "value": "oklch(0.924 0.115 95.7)"
      },
      {
        "step": "300",
        "value": "oklch(0.879 0.153 91.6)"
      },
      {
        "step": "400",
        "value": "oklch(0.837 0.164 84.4)"
      },
      {
        "step": "500",
        "value": "oklch(0.769 0.165 70.1)"
      },
      {
        "step": "600",
        "value": "oklch(0.666 0.157 58.3)"
      },
      {
        "step": "700",
        "value": "oklch(0.555 0.146 49)"
      },
      {
        "step": "800",
        "value": "oklch(0.473 0.125 46.2)"
      },
      {
        "step": "900",
        "value": "oklch(0.414 0.105 45.9)"
      },
      {
        "step": "950",
        "value": "oklch(0.279 0.074 45.6)"
      }
    ]
  },
  {
    "name": "yellow",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.987 0.026 102.2)"
      },
      {
        "step": "100",
        "value": "oklch(0.973 0.069 103.2)"
      },
      {
        "step": "200",
        "value": "oklch(0.945 0.124 101.5)"
      },
      {
        "step": "300",
        "value": "oklch(0.905 0.166 98.1)"
      },
      {
        "step": "400",
        "value": "oklch(0.861 0.173 91.9)"
      },
      {
        "step": "500",
        "value": "oklch(0.795 0.162 86)"
      },
      {
        "step": "600",
        "value": "oklch(0.681 0.142 75.8)"
      },
      {
        "step": "700",
        "value": "oklch(0.554 0.121 66.4)"
      },
      {
        "step": "800",
        "value": "oklch(0.476 0.103 61.9)"
      },
      {
        "step": "900",
        "value": "oklch(0.421 0.09 57.7)"
      },
      {
        "step": "950",
        "value": "oklch(0.286 0.064 53.8)"
      }
    ]
  },
  {
    "name": "lime",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.986 0.031 120.8)"
      },
      {
        "step": "100",
        "value": "oklch(0.967 0.066 122.3)"
      },
      {
        "step": "200",
        "value": "oklch(0.938 0.122 124.3)"
      },
      {
        "step": "300",
        "value": "oklch(0.897 0.179 126.7)"
      },
      {
        "step": "400",
        "value": "oklch(0.849 0.207 128.8)"
      },
      {
        "step": "500",
        "value": "oklch(0.768 0.204 130.8)"
      },
      {
        "step": "600",
        "value": "oklch(0.648 0.175 131.7)"
      },
      {
        "step": "700",
        "value": "oklch(0.532 0.141 131.6)"
      },
      {
        "step": "800",
        "value": "oklch(0.453 0.113 130.9)"
      },
      {
        "step": "900",
        "value": "oklch(0.405 0.096 131.1)"
      },
      {
        "step": "950",
        "value": "oklch(0.274 0.069 132.1)"
      }
    ]
  },
  {
    "name": "green",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.982 0.018 155.8)"
      },
      {
        "step": "100",
        "value": "oklch(0.962 0.043 156.7)"
      },
      {
        "step": "200",
        "value": "oklch(0.925 0.081 156)"
      },
      {
        "step": "300",
        "value": "oklch(0.871 0.136 154.4)"
      },
      {
        "step": "400",
        "value": "oklch(0.8 0.182 151.7)"
      },
      {
        "step": "500",
        "value": "oklch(0.723 0.192 149.6)"
      },
      {
        "step": "600",
        "value": "oklch(0.627 0.17 149.2)"
      },
      {
        "step": "700",
        "value": "oklch(0.527 0.137 150.1)"
      },
      {
        "step": "800",
        "value": "oklch(0.448 0.108 151.3)"
      },
      {
        "step": "900",
        "value": "oklch(0.393 0.09 152.5)"
      },
      {
        "step": "950",
        "value": "oklch(0.266 0.063 152.9)"
      }
    ]
  },
  {
    "name": "emerald",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.979 0.021 166.1)"
      },
      {
        "step": "100",
        "value": "oklch(0.95 0.051 163.1)"
      },
      {
        "step": "200",
        "value": "oklch(0.905 0.089 164.2)"
      },
      {
        "step": "300",
        "value": "oklch(0.845 0.13 165)"
      },
      {
        "step": "400",
        "value": "oklch(0.773 0.153 163.2)"
      },
      {
        "step": "500",
        "value": "oklch(0.696 0.149 162.5)"
      },
      {
        "step": "600",
        "value": "oklch(0.596 0.127 163.2)"
      },
      {
        "step": "700",
        "value": "oklch(0.508 0.105 165.6)"
      },
      {
        "step": "800",
        "value": "oklch(0.432 0.086 166.9)"
      },
      {
        "step": "900",
        "value": "oklch(0.378 0.073 168.9)"
      },
      {
        "step": "950",
        "value": "oklch(0.262 0.049 172.6)"
      }
    ]
  },
  {
    "name": "teal",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.984 0.014 180.7)"
      },
      {
        "step": "100",
        "value": "oklch(0.953 0.05 180.8)"
      },
      {
        "step": "200",
        "value": "oklch(0.91 0.093 180.4)"
      },
      {
        "step": "300",
        "value": "oklch(0.855 0.125 181.1)"
      },
      {
        "step": "400",
        "value": "oklch(0.785 0.133 181.9)"
      },
      {
        "step": "500",
        "value": "oklch(0.704 0.123 182.5)"
      },
      {
        "step": "600",
        "value": "oklch(0.6 0.104 184.7)"
      },
      {
        "step": "700",
        "value": "oklch(0.511 0.086 186.4)"
      },
      {
        "step": "800",
        "value": "oklch(0.437 0.071 188.2)"
      },
      {
        "step": "900",
        "value": "oklch(0.386 0.059 188.4)"
      },
      {
        "step": "950",
        "value": "oklch(0.277 0.045 192.5)"
      }
    ]
  },
  {
    "name": "cyan",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.984 0.019 200.9)"
      },
      {
        "step": "100",
        "value": "oklch(0.956 0.044 203.4)"
      },
      {
        "step": "200",
        "value": "oklch(0.917 0.077 205)"
      },
      {
        "step": "300",
        "value": "oklch(0.865 0.115 207.1)"
      },
      {
        "step": "400",
        "value": "oklch(0.797 0.134 211.5)"
      },
      {
        "step": "500",
        "value": "oklch(0.715 0.126 215.2)"
      },
      {
        "step": "600",
        "value": "oklch(0.609 0.111 221.7)"
      },
      {
        "step": "700",
        "value": "oklch(0.52 0.094 223.1)"
      },
      {
        "step": "800",
        "value": "oklch(0.45 0.077 224.3)"
      },
      {
        "step": "900",
        "value": "oklch(0.398 0.066 227.4)"
      },
      {
        "step": "950",
        "value": "oklch(0.302 0.054 229.7)"
      }
    ]
  },
  {
    "name": "sky",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.977 0.012 236.6)"
      },
      {
        "step": "100",
        "value": "oklch(0.951 0.025 236.8)"
      },
      {
        "step": "200",
        "value": "oklch(0.901 0.055 230.9)"
      },
      {
        "step": "300",
        "value": "oklch(0.828 0.101 230.3)"
      },
      {
        "step": "400",
        "value": "oklch(0.754 0.139 232.7)"
      },
      {
        "step": "500",
        "value": "oklch(0.685 0.148 237.3)"
      },
      {
        "step": "600",
        "value": "oklch(0.588 0.139 242)"
      },
      {
        "step": "700",
        "value": "oklch(0.5 0.119 242.7)"
      },
      {
        "step": "800",
        "value": "oklch(0.443 0.1 240.8)"
      },
      {
        "step": "900",
        "value": "oklch(0.391 0.085 240.9)"
      },
      {
        "step": "950",
        "value": "oklch(0.293 0.063 243.2)"
      }
    ]
  },
  {
    "name": "indigo",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.962 0.018 272.3)"
      },
      {
        "step": "100",
        "value": "oklch(0.93 0.033 272.8)"
      },
      {
        "step": "200",
        "value": "oklch(0.87 0.062 274)"
      },
      {
        "step": "300",
        "value": "oklch(0.785 0.104 274.7)"
      },
      {
        "step": "400",
        "value": "oklch(0.68 0.158 276.9)"
      },
      {
        "step": "500",
        "value": "oklch(0.585 0.204 277.1)"
      },
      {
        "step": "600",
        "value": "oklch(0.511 0.23 277)"
      },
      {
        "step": "700",
        "value": "oklch(0.457 0.215 277)"
      },
      {
        "step": "800",
        "value": "oklch(0.398 0.177 277.4)"
      },
      {
        "step": "900",
        "value": "oklch(0.359 0.135 278.7)"
      },
      {
        "step": "950",
        "value": "oklch(0.257 0.086 281.3)"
      }
    ]
  },
  {
    "name": "violet",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.969 0.016 293.8)"
      },
      {
        "step": "100",
        "value": "oklch(0.943 0.028 294.6)"
      },
      {
        "step": "200",
        "value": "oklch(0.894 0.055 293.3)"
      },
      {
        "step": "300",
        "value": "oklch(0.811 0.101 293.6)"
      },
      {
        "step": "400",
        "value": "oklch(0.709 0.159 293.5)"
      },
      {
        "step": "500",
        "value": "oklch(0.606 0.219 292.7)"
      },
      {
        "step": "600",
        "value": "oklch(0.541 0.247 293)"
      },
      {
        "step": "700",
        "value": "oklch(0.491 0.241 292.6)"
      },
      {
        "step": "800",
        "value": "oklch(0.432 0.211 292.8)"
      },
      {
        "step": "900",
        "value": "oklch(0.38 0.178 293.7)"
      },
      {
        "step": "950",
        "value": "oklch(0.283 0.135 291.1)"
      }
    ]
  },
  {
    "name": "purple",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.977 0.014 308.3)"
      },
      {
        "step": "100",
        "value": "oklch(0.946 0.033 307.2)"
      },
      {
        "step": "200",
        "value": "oklch(0.902 0.06 306.7)"
      },
      {
        "step": "300",
        "value": "oklch(0.827 0.108 306.4)"
      },
      {
        "step": "400",
        "value": "oklch(0.722 0.177 305.5)"
      },
      {
        "step": "500",
        "value": "oklch(0.627 0.233 303.9)"
      },
      {
        "step": "600",
        "value": "oklch(0.558 0.252 302.3)"
      },
      {
        "step": "700",
        "value": "oklch(0.496 0.237 301.9)"
      },
      {
        "step": "800",
        "value": "oklch(0.438 0.198 303.7)"
      },
      {
        "step": "900",
        "value": "oklch(0.381 0.166 305)"
      },
      {
        "step": "950",
        "value": "oklch(0.291 0.143 302.7)"
      }
    ]
  },
  {
    "name": "fuchsia",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.977 0.017 320.1)"
      },
      {
        "step": "100",
        "value": "oklch(0.952 0.036 318.9)"
      },
      {
        "step": "200",
        "value": "oklch(0.903 0.073 319.6)"
      },
      {
        "step": "300",
        "value": "oklch(0.833 0.132 321.4)"
      },
      {
        "step": "400",
        "value": "oklch(0.748 0.207 322.2)"
      },
      {
        "step": "500",
        "value": "oklch(0.667 0.259 322.1)"
      },
      {
        "step": "600",
        "value": "oklch(0.591 0.257 322.9)"
      },
      {
        "step": "700",
        "value": "oklch(0.518 0.226 323.9)"
      },
      {
        "step": "800",
        "value": "oklch(0.452 0.192 324.6)"
      },
      {
        "step": "900",
        "value": "oklch(0.401 0.16 325.6)"
      },
      {
        "step": "950",
        "value": "oklch(0.293 0.131 325.7)"
      }
    ]
  },
  {
    "name": "pink",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.971 0.014 343.2)"
      },
      {
        "step": "100",
        "value": "oklch(0.948 0.028 342.3)"
      },
      {
        "step": "200",
        "value": "oklch(0.899 0.059 343.2)"
      },
      {
        "step": "300",
        "value": "oklch(0.823 0.11 346)"
      },
      {
        "step": "400",
        "value": "oklch(0.725 0.175 349.8)"
      },
      {
        "step": "500",
        "value": "oklch(0.656 0.212 354.3)"
      },
      {
        "step": "600",
        "value": "oklch(0.592 0.218 0.6)"
      },
      {
        "step": "700",
        "value": "oklch(0.525 0.199 4)"
      },
      {
        "step": "800",
        "value": "oklch(0.459 0.17 3.8)"
      },
      {
        "step": "900",
        "value": "oklch(0.408 0.144 2.4)"
      },
      {
        "step": "950",
        "value": "oklch(0.284 0.105 3.9)"
      }
    ]
  },
  {
    "name": "rose",
    "swatches": [
      {
        "step": "50",
        "value": "oklch(0.969 0.015 12.4)"
      },
      {
        "step": "100",
        "value": "oklch(0.941 0.03 12.6)"
      },
      {
        "step": "200",
        "value": "oklch(0.892 0.056 10)"
      },
      {
        "step": "300",
        "value": "oklch(0.81 0.106 11.6)"
      },
      {
        "step": "400",
        "value": "oklch(0.719 0.169 13.4)"
      },
      {
        "step": "500",
        "value": "oklch(0.645 0.215 16.4)"
      },
      {
        "step": "600",
        "value": "oklch(0.586 0.222 17.6)"
      },
      {
        "step": "700",
        "value": "oklch(0.514 0.198 16.9)"
      },
      {
        "step": "800",
        "value": "oklch(0.455 0.171 13.7)"
      },
      {
        "step": "900",
        "value": "oklch(0.41 0.15 10.3)"
      },
      {
        "step": "950",
        "value": "oklch(0.271 0.101 12.1)"
      }
    ]
  }
]
